
namespace Sla.CORE
{
    /// \brief The lowest level error generated by the decompiler
    /// This is the base error for all exceptions thrown by the
    /// decompiler.  This underived form is thrown for very low
    /// level errors that immediately abort decompilation (usually
    /// for just a single function).
    public class LowlevelError : Exception
    {
        /// Initialize the error with an explanatory string
        internal LowlevelError(string s)
            : base(s)
        {
        }

        internal LowlevelError(string s, Exception innerException)
            : base(s, innerException)
        {
        }
    }
}

